/**
 * Ad creatives generated with the Image Ads Strategist GPT.
 *
 * Generated by `scripts/sync-ads.mjs` — do not hand-edit. Re-run the script
 * to add, replace or remove creatives:
 *
 *   node scripts/sync-ads.mjs ~/path/to/your/ad-images
 *
 * Empty until they're imported. While it's empty the image-ads module falls
 * back to its labelled AssetSlot, so the layout is already reserved and
 * nothing shifts when the real ads land.
 */

export type AdCreative = {
  src: string;
  width: number;
  height: number;
  /** Smaller widths that exist on disk, for the srcset. */
  widths: number[];
  alt: string;
};

export const adCreatives: readonly AdCreative[] = [];
