/**
 * Ad creatives generated with the Image Ads Strategist GPT.
 *
 * Generated by `scripts/sync-ads.mjs` — do not hand-edit. Re-run the script
 * to add, replace or remove creatives.
 *
 * Alt text is intentionally generic: these are marketing artwork, and the
 * headline inside each image is not readable to a screen reader anyway. If you
 * want them described individually, edit `alt` per entry and the script will
 * not overwrite your wording as long as you keep the file list unchanged.
 */

export type AdCreative = {
  src: string;
  width: number;
  height: number;
  /** Smaller widths that exist on disk, for the srcset. */
  widths: number[];
  alt: string;
};

export const adCreatives: readonly AdCreative[] = [
  {
    "src": "/ads/ad-01.webp",
    "width": 1400,
    "height": 1812,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 1 of 11, generated with the Image Ads Strategist GPT"
  },
  {
    "src": "/ads/ad-02.webp",
    "width": 1400,
    "height": 1812,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 2 of 11, generated with the Image Ads Strategist GPT"
  },
  {
    "src": "/ads/ad-03.webp",
    "width": 1400,
    "height": 1812,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 3 of 11, generated with the Image Ads Strategist GPT"
  },
  {
    "src": "/ads/ad-04.webp",
    "width": 1400,
    "height": 1812,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 4 of 11, generated with the Image Ads Strategist GPT"
  },
  {
    "src": "/ads/ad-05.webp",
    "width": 1400,
    "height": 1812,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 5 of 11, generated with the Image Ads Strategist GPT"
  },
  {
    "src": "/ads/ad-06.webp",
    "width": 1400,
    "height": 1812,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 6 of 11, generated with the Image Ads Strategist GPT"
  },
  {
    "src": "/ads/ad-07.webp",
    "width": 1400,
    "height": 1812,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 7 of 11, generated with the Image Ads Strategist GPT"
  },
  {
    "src": "/ads/ad-08.webp",
    "width": 900,
    "height": 1200,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 8 of 11, generated with the Image Ads Strategist GPT"
  },
  {
    "src": "/ads/ad-09.webp",
    "width": 900,
    "height": 1200,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 9 of 11, generated with the Image Ads Strategist GPT"
  },
  {
    "src": "/ads/ad-10.webp",
    "width": 900,
    "height": 1200,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 10 of 11, generated with the Image Ads Strategist GPT"
  },
  {
    "src": "/ads/ad-11.webp",
    "width": 900,
    "height": 1200,
    "widths": [
      400,
      700
    ],
    "alt": "Ad creative 11 of 11, generated with the Image Ads Strategist GPT"
  }
];
