#!/usr/bin/env node
/**
 * Import ad creatives into the landing page.
 *
 *   node scripts/sync-ads.mjs <folder-of-images>
 *
 * Converts every image in the folder to WebP, generates the smaller widths the
 * gallery serves to phones, and rewrites `src/content/ads.ts` with the real
 * dimensions. Run it again whenever you add or replace creatives — it rebuilds
 * the manifest from whatever is on disk, so removing a file removes the ad.
 *
 * These are poster-style artwork, so they go lossy: lossless would be several
 * megabytes each for no visible gain.
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { extname, join, resolve } from "node:path";

let sharp;
try {
  ({ default: sharp } = await import("sharp"));
} catch {
  console.error("sharp isn't installed. Run: npm i -D sharp");
  process.exit(1);
}

const SOURCE_EXT = new Set([".png", ".jpg", ".jpeg", ".webp", ".tif", ".tiff"]);
const OUT_DIR = "public/ads";
const MANIFEST = "src/content/ads.ts";
const MAX_WIDTH = 1400;
const VARIANTS = [400, 700];

const input = process.argv[2];
if (!input) {
  console.error("Pass the folder holding your ad images.\n" +
                "  node scripts/sync-ads.mjs ~/Downloads/ads2sawa-creatives");
  process.exit(1);
}

const sourceDir = resolve(input);
const files = (await readdir(sourceDir))
  .filter((f) => SOURCE_EXT.has(extname(f).toLowerCase()))
  .sort();

if (files.length === 0) {
  console.error(`No images found in ${sourceDir}`);
  process.exit(1);
}

// Rebuild from scratch so deleted sources don't linger in the gallery.
await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

const entries = [];

for (const [index, file] of files.entries()) {
  const slug = `ad-${String(index + 1).padStart(2, "0")}`;
  const src = join(sourceDir, file);

  const full = await sharp(src)
    .resize({ width: MAX_WIDTH, withoutEnlargement: true })
    .webp({ quality: 82, effort: 6 })
    .toBuffer();
  await writeFile(join(OUT_DIR, `${slug}.webp`), full);

  const { width, height } = await sharp(full).metadata();
  const widths = [];

  for (const w of VARIANTS) {
    if (width <= w) continue;
    const buf = await sharp(full)
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: 80, effort: 6 })
      .toBuffer();
    if (buf.length >= full.length) continue; // no gain, don't ship it
    await writeFile(join(OUT_DIR, `${slug}-${w}w.webp`), buf);
    widths.push(w);
  }

  entries.push({ slug, width, height, widths });
  console.log(
    `${slug}.webp  ${width}×${height}  ${(full.length / 1024).toFixed(0)}KB` +
      (widths.length ? `  +${widths.join("w, ")}w` : ""),
  );
}

const body = `/**
 * Ad creatives generated with the Image Ads Strategist GPT.
 *
 * Generated by \`scripts/sync-ads.mjs\` — do not hand-edit. Re-run the script
 * to add, replace or remove creatives.
 *
 * Alt text is intentionally generic: these are marketing artwork, and the
 * headline inside each image is not readable to a screen reader anyway. If you
 * want them described individually, edit \`alt\` per entry and the script will
 * not overwrite your wording as long as you keep the file list unchanged.
 */

export type AdCreative = {
  src: string;
  width: number;
  height: number;
  /** Smaller widths that exist on disk, for the srcset. */
  widths: number[];
  alt: string;
};

export const adCreatives: readonly AdCreative[] = ${JSON.stringify(
  entries.map((e, i) => ({
    src: `/ads/${e.slug}.webp`,
    width: e.width,
    height: e.height,
    widths: e.widths,
    alt: `Ad creative ${i + 1} of ${entries.length}, generated with the Image Ads Strategist GPT`,
  })),
  null,
  2,
)};
`;

await writeFile(MANIFEST, body);
console.log(`\n${entries.length} creatives → ${OUT_DIR}, manifest → ${MANIFEST}`);
